server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hravada/spring-cloud-config-store.git
          search-paths:
           - '*service'



